#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

# stolen from: https://github.com/linuxserver/docker-baseimage-alpine/blob/master/root/etc/cont-init.d/01-envfile
# Export env vars from /run/s6/container_environment/SECRET__<varname> files (double underscores)
# Requires with-contenv
if find /run/s6/container_environment/SECRET__* -maxdepth 1 > /dev/null 2>&1; then
    for FILENAME in /run/s6/container_environment/*;
    do
        if [[ "${FILENAME##*/}" == "SECRET__"* ]];
        then
            SECRETFILE="$(cat ${FILENAME})";
            if [[ -f "${SECRETFILE}" ]];
            then
                FILESTRIP=${FILENAME//SECRET__/};
                cat "${SECRETFILE}" >"${FILESTRIP}";
                vecho "${FILESTRIP##*/} set from ${FILENAME##*/}";
            else
                vecho "Cannot find secret in ${FILENAME##*/}";
            fi;
        fi;
    done;
fi;
