#!/usr/bin/with-contenv bash
set -e

# stolen from: https://github.com/linuxserver/docker-baseimage-alpine/blob/master/root/etc/cont-init.d/01-envfile
# Export env vars from /run/s6/container_environment/SECRET__<varname> files
# Requires with-contenv
if find /run/s6/container_environment/SECRET__* -maxdepth 1 > /dev/null 2>&1; then
    for FILENAME in /run/s6/container_environment/*;
    do
        if [[ "${FILENAME##*/}" == "SECRET__"* ]];
        then
            SECRETFILE="$(cat ${FILENAME})";
            if [[ -f "${SECRETFILE}" ]];
            then
                FILESTRIP=${FILENAME//SECRET__/};
                cat "${SECRETFILE}" >"${FILESTRIP}";
                echo "[file-to-env] ${FILESTRIP##*/} set from ${FILENAME##*/}";
            else
                echo "[file-to-env] cannot find secret in ${FILENAME##*/}";
            fi;
        fi;
    done;
fi;
