ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}

ARG BUILD_DATE
ARG DOCKEREPO=frommakefile
ARG USERNAME=frommakefile
ARG VCS_REF

LABEL org.label-schema.schema-version="1.0" \
    org.label-schema.vcs-url="https://github.com/$USERNAME/$DOCKEREPO" \
    org.label-schema.name=$DOCKEREPO \
    org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.vendor=$USERNAME

RUN apk add --no-cache --purge -uU curl && \
    VERSION=$(curl -SL https://api.github.com/repos/just-containers/s6-overlay/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]' | sed -e 's_v__') && \
    echo "using s6 version: $VERSION" && \
	curl -o /tmp/s6-overlay-armhf.tar.gz -jkSL https://github.com/just-containers/s6-overlay/releases/download/v${VERSION}/s6-overlay-armhf.tar.gz && \
	tar xzf /tmp/s6-overlay-armhf.tar.gz -C / && \
	rm -rf /var/cache/apk/* /tmp/*

ENTRYPOINT ["/bin/bash"]
